[package]
name = "xdg-desktop-parser"
version = "0.1.0"
edition = "2018"
license = "LGPL-2.1-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
onig = "6.1.1"
